# Generated by Django 4.0.1 on 2022-09-14 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Başlık')),
                ('description', models.TextField(max_length=500, verbose_name='Açıklama')),
                ('cover_image', models.FileField(upload_to='images', verbose_name='Kapak Resmi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif Mi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Metin')),
                ('order_number', models.IntegerField(verbose_name='Sıra No')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='blog_app.blogpost', verbose_name='Blog Yazısı')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Kod')),
                ('order_number', models.IntegerField(verbose_name='Sıra No')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='blog_app.blogpost', verbose_name='Blog Yazısı')),
            ],
        ),
    ]
