# Generated by Django 4.0.1 on 2022-09-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Kod', 'verbose_name_plural': 'Kodlar'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Metin', 'verbose_name_plural': 'Metinler'},
        ),
    ]
