# Generated by Django 4.0.1 on 2022-09-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogpost_options_alter_code_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.FileField(upload_to='images/', verbose_name='Kapak Resmi'),
        ),
    ]
